SUPABASE_URL = "https://omxoueyyhexjatajaiuo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9teG91ZXl5aGV4amF0YWphaXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDM4ODAsImV4cCI6MjA1ODcxOTg4MH0.vPk_bdB8HA0M8MoqmffAAgv6R2e9_uq4NsQkwWih9IE"

[general]
OPENAI_API_KEY="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"
