SUPABASE_URL = "https://tdfhmpidnnfjycjewmla.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZmhtcGlkbm5manljamV3bWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDE2MzgsImV4cCI6MjA1OTQxNzYzOH0.Bto42cOX7O5szGjcWa-AEtfhbrJl2sHo1sy7PC0PetI"
[general]
OPENAI_API_KEY="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"
